if(NOT DEFINED PACKAGE_NAME)
	message(FATAL_ERROR "PACKAGE_NAME variable is not set")
endif()

if(NOT DEFINED PACKAGE_SOURCES)
	message(FATAL_ERROR "PACKAGE_SOURCES variable is not set")
endif()

string(TOLOWER ${PACKAGE_NAME} PACKAGE_LOWER_NAME)
string(TOUPPER ${PACKAGE_NAME} PACKAGE_UPPER_NAME)

if(NOT DEFINED PACKAGE_EXE_NAME)
	set(PACKAGE_EXE_NAME ${PACKAGE_LOWER_NAME})
endif()

if(NOT DEFINED PACKAGE_ICON_NAME)
	set(PACKAGE_ICON_NAME ${PACKAGE_NAME})
endif()

if(NOT DEFINED PACKAGE_DESKTOP_FILE)
	set(PACKAGE_DESKTOP_FILE ${PACKAGE_LOWER_NAME}.desktop)
endif()

if(NOT DEFINED PACKAGE_JAVA_URL)
	set(PACKAGE_JAVA_URL ${PACKAGE_LOWER_NAME})
endif()
